### PR TITLE
Implemented Accessibility Evaluation and Modified the Relevant Changes

### PR DESCRIPTION
**Pull request by ometman**
**Accessibility Evaluation Report**

1. Page Titles
Accessibility guidelines - in accordance with guidelines 
Content - accurately descriptive
Other browsers - visible on all browsers

2. Image text alternatives
Total 36 images
both for mobile and desktop
alternative text applicable in all cases

3. Text headings
two sections for mobile - h1 first and h2 second
four sections for desktop - h1 first and four h2 second 
no h3

4. Color Contrast
health score tester: score 81% passed
placeholder contrast ratio: 6.11 : 1 

5. Resize
by default: all anchor elements are accessible with keyboard use
use of Aria interaction method: all html elements become more accessible

6. Interaction
form: three textfields accessible with keyboard Tab
labels: include inside the text
required fields: not indicated
asterisks: not indicated
general instructions: not indicated
dates: not available / not applicable
detail error handling: validation messages require javascript
html validation: no issue

7. Moving Content
Moving h1 - applicable / no issue
Distraction - not applicable
Flashing and blinking - no issue

8. Multimedia
Not applicable / no issue

9. Basic structure
CSS turn-off - in order
Menu-button turned-off - structure remains intact
Portfolio source image - alternative text displayed descriptively

**Accessibility Changes** 

1. Image text alternatives:

- Alternative texts for images improved appropriately

2. Heading:

- Heading structure improved with h3 tag.
- Added h3 tag to social media and technology areas.
- h3 tag replaced paragraph (p) tag.

3. Forms, labels, and errors

- Added instructions for filling the form.
- Added general and individual field instructions.
- Add labels to form elements 
- Labels were set to  invisible
- Required fields are indicated by asterisks.
- Border color added for validation.

4. Moving, Flashing, or Blinking Content:

- Only the Primary Heading is refactored to move 
- appropriately, without distraction.

### CODE REVIEW

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
Hi @ometman ☺️, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 


you-are-near

## Highlights ✔️
- [x] Good writing the report on accessibility
- [x] Descriptive READme file in a professional way.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow

 ## Required Changes ♻️

- [ ] Kindly 😃 try to fix the Color contrast which refers to the difference between the foreground and background colors. Meeting color contrast requirements 💯 is one of the most important accessibility [Click here for more info](https://www.editorx.com/shaping-design/article/how-to-check-the-accessibility-of-a-website)⤵️
- [ ] Kindly 😊 try to fix Heading levels should have a meaningful hierarchy Ensure headings are in a logical order. For example, check that all headings are marked 💯with h1 through h6 elements and that these are ordered hierarchically. For example, the heading level following an h1 element should be an h2 element, not an h3 element. Finally, don't use heading markup on the text that isn't actually a heading.

> Take a look here : 


| Your accessibility for heading descending | Your accessibility for contrast| 
| --- | --- |
|   image   |    image   |

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ometman** [comment]
Your review is good.  Changes will done. Thanks

**Review by KanzaTahreem — CHANGES_REQUESTED** [review]
# Changes Required 🔁

Hi @ometman 👋

Good job implementing the changes suggested by the previous reviewer.
**_You have come a long way to make it here and a little more effort can make your project perfect. You are almost there 💪 🏁_**

so_close

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅  Good use of GitHub flow.
- ✅ Well done with the branch name
- ✅ Excellent PR description, well done!

However, there is always room for improvement.

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

- [x] Wonderful job adding color to each element in your portfolio 🥇. As suggested by the previous reviewer, please makes sure to fix the color contrast. This is because there are some people who cannot read the text if there is not sufficient contrast between the text and the background, as an accessibility requirement, please make sure that your page has the correct contrast ratio 👍. You can use [this aditus tool](https://www.aditus.io/button-contrast-checker/) to help you to check the color contrast 💪
 - [x] Alternatively you can also use **_WCAG Contrast checker_** or **_WebDev Toolbar_** (for windows)

### **_From WebDev Toolbar 👇_**
| Before | Now | 
|----------|----------|
|  image |  image | 
### **_From WCAG Contrast checker 👇_**

| Before | Now | 
|----------|----------| 
| image |  image | 

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Zuhaib042 — APPROVED** [review]
Hi @ometman , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
approve

 ## Highlights
✅ Correct use of GitHub flow.
✅ Professional PR.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ometman** [comment]
Thank you. Further suggestions will surely be looked at and worked on.

**Pull request merged**
